kind: "Policy"
apiVersion: "authentication.istio.io/v1alpha1"
metadata:
  name: "receiver-permissive"
  namespace: "{{namespace}}"
spec:
  targets:
  - name: receiver
  peers:
  - mtls:
      mode: PERMISSIVE
