kind: Service
apiVersion: v1
metadata:
  name: ui
  namespace: "{{namespace}}"
  lables:
    app: ui
spec:
  selector:
    app: ui
  ports:
  - name: http-ui
    port: 3000
    targetPort: 3000
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: ui
  namespace: "{{namespace}}"
  labels:
    app: ui
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: ui
        version: v1
    spec:
      containers:
      - name: ui
        image: " "
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
  triggers:
    - type: "ConfigChange"
    - type: "ImageChange"
      imageChangeParams:
        automatic: true
        containerNames:
          - "ui"
        from:
          kind: "ImageStreamTag"
          name: "ui:0.1"