apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ui
  namespace: "{{namespace}}"
spec:
  hosts:
  - frontend.apps.a.okto.ocplab.io
  - ui
  gateways:
  - nemo-gateway
  http:
  - route:
    - destination:
        host: ui
        subset: v1
