---
- name: Prerequest
  hosts: 127.0.0.1
  connection: local
  gather_facts: no
  vars:
    mtls_mode: ISTIO_MUTUAL
  tasks:
    - name: nvui
      import_role:
        name: ui-header-routing
      tags: nvui
    - name: delay
      import_role:
        name: likes-delay
      tags: delay
    - name: abort
      import_role:
        name: likes-abort
      tags: abort
    - name: cb
      import_role:
        name: feed-cb
      tags: cb
    - name: mirror
      import_role:
        name: feed-mirror
      tags: mirror
    - name: filters
      import_role:
        name: identity-envoy-filters
      tags: filters
    - name: identitynv-weight-native
      import_role:
        name: identitynv-weight-native
      tags: weight-native
    - name: weight-istio
      import_role:
        name: identitynv-weight-istio
      tags: weight-istio
    - name: nvui-weight-istio
      import_role:
        name: nvui-weight-istio
      tags: nvui-weight-istio
