- name:  Identity ImageStream
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/identity-is.yaml') }}"

- name:  Identity BuildConfig
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/identity-bc.yaml') }}"

- name: Fetch build build state
  k8s_facts:
    kind: BuildConfig
    api_version: build.openshift.io/v1
    namespace: "{{namespace}}"
    name: "{{identity_bc_name}}"
  register: build_config

- name: Build Identity docker image if it's a fresh setup
  shell: "oc start-build {{identity_bc_name}} -n {{namespace}}"
  when:
    - build_config.resources | length > 0
    - build_config.resources[0].status.lastVersion | int == 0

# Add Postgres objects
- name:  Identity Postgres
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/pg.yaml') }}"

# App objects
- name:  Identity Deployment
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/dep.yaml') }}"

# Istio objects
- name:  DestinationRule
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/drule.yaml') }}"

- name:  VirtualService
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/vs.yaml') }}"
