# Add Postgres objects
- name:  Identity Postgres
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/pg.yaml') }}"

# App objects
- name:  Identity Deployment
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/dep.yaml') }}"

# Istio objects
- name:  DestinationRule
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/drule.yaml') }}"

- name:  VirtualService
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/vs.yaml') }}"

- name:  Identity DestinationRule for Istio NS
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/drule-for-istio-ns.yaml') }}"

- name:  Identity Policy
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/policy.yaml') }}"
