# App objects
- name:  Identity NV Deployment
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/dep.yaml') }}"

- name: Identity NV VirtualService
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/vs.yaml') }}"

- name:  Identity DestinationRule for Istio NS
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/drule-for-istio-ns.yaml') }}"
