apiVersion: v1
kind: DeploymentConfig
metadata:
  name: identity-new-version
  namespace: "{{namespace}}"
  labels:
    app: identity
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: identity
        version: v2
    spec:
      containers:
      - name: identity
        image: " "
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        ports:
        - containerPort: 8080
  triggers:
    - type: "ConfigChange"
    - type: "ImageChange"
      imageChangeParams:
        automatic: true
        containerNames:
          - "identity"
        from:
          kind: "ImageStreamTag"
          name: "identity-new-version:0.1"