- name:  Links ImageStream
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/links-is.yaml') }}"

- name:  Links BuildConfig
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/links-bc.yaml') }}"

- name: Fetch build config state
  k8s_facts:
    kind: BuildConfig
    api_version: build.openshift.io/v1
    namespace: "{{namespace}}"
    name: "{{links_bc_name}}"
  register: build_config

- name: Build Links docker image if it's a fresh setup
  shell: "oc start-build {{links_bc_name}} -n {{namespace}}"
  when:
    - build_config.resources | length > 0
    - build_config.resources[0].status.lastVersion | int == 0

# App objects
- name:  MongDB instace
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/mongo-dep.yaml') }}"

# App objects
- name:  Links Deployment
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/dep.yaml') }}"

# Istio objects
- name:  Links DestinationRule
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/drule.yaml') }}"

- name:  Links VirtualService
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/vs.yaml') }}"
