# App objects
- name:  MongoDB instace
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/mongo-dep.yaml') }}"

# App objects
- name:  Links Deployment
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/dep.yaml') }}"

# Istio objects
- name:  Links DestinationRule
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/drule.yaml') }}"

- name:  Links VirtualService
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/vs.yaml') }}"
