apiVersion: v1
kind: ImageStream
metadata:
    name: mongo
    namespace: {{namespace}}
spec:
    tags:
    - from:
          kind: DockerImage
          name: mongo
      name: latest
      importPolicy:
          scheduled: true
