apiVersion: v1
kind: ImageStream
metadata:
  name: comments
  namespace: "{{namespace}}"
spec:
    tags:
    - from:
          kind: DockerImage
          name: "docker-registry.default.svc:5000/{{namespace}}/comments"
      name: latest
      importPolicy:
          scheduled: true
