kind: "BuildConfig"
apiVersion: "build.openshift.io/v1"
metadata:
  name: "identity"
  namespace: "{{namespace}}"
spec:
  runPolicy: "Serial"
  source:
    git:
      uri: "https://github.com/Dimss/nemo-identity-service.git"
  strategy:
    sourceStrategy:
      from:
        kind: "ImageStreamTag"
        name: "java:8"
        namespace: "openshift"
  output:
    to:
      kind: "ImageStreamTag"
      name: "identity:0.1"
