apiVersion: v1
kind: ImageStream
metadata:
  name: identity-new-version
  namespace: "{{namespace}}"
spec:
    tags:
    - from:
          kind: DockerImage
          name: "docker-registry.default.svc:5000/{{namespace}}/identity-new-version"
      name: latest
      importPolicy:
          scheduled: true
