apiVersion: v1
kind: ImageStream
metadata:
    name: ui-new-version
    namespace: "{{namespace}}"
spec:
    tags:
    - from:
          kind: DockerImage
          name: docker-registry.default.svc:5000/nemo/ui-new-version
      name: latest
      importPolicy:
          scheduled: true
