kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "receiver"
  namespace: "{{namespace}}"
spec:
  runPolicy: "Serial"
  source:
    git:
      uri: "https://github.com/Dimss/nemo-receiver.git"
  strategy:
    sourceStrategy:
      from:
        kind: "ImageStreamTag"
        name: "java:8"
        namespace: "openshift"
  output:
    to:
      kind: "ImageStreamTag"
      name: "receiver:0.1"
