kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "{{app_name}}"
  namespace: "{{namespace}}"
spec:
  runPolicy: "Serial"
  source:
    git:
      uri: "{{git}}"
  strategy:
    sourceStrategy:
      from:
        kind: "ImageStreamTag"
        name: "{{from_istag}}"
        namespace: "openshift"
  output:
    to:
      kind: "ImageStreamTag"
      name: "{{app_istag}}"
