apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: feed
  namespace: "{{namespace}}"
spec:
  host: feed
  trafficPolicy:
    tls:
      mode: "{{mtls_mode}}"
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v1d
    labels:
      version: v1d
