# Project level settings
- name: Project setup
  shell: |
    oc new-project {{namespace}}
    oc adm policy add-scc-to-user anyuid -z default -n {{namespace}}
    oc adm policy add-scc-to-user privileged -z default -n {{namespace}}
  ignore_errors: yes
#
## ImageStreams for building application containres
#- name:  OpenJDK18 ImageStream
#  k8s:
#    state: "{{state}}"
#    definition: "{{ lookup('template', 'templates/0-openjdk18-is.yaml') }}"
#
#- name:  Python36 ImageStream
#  k8s:
#    state: "{{state}}"
#    definition: "{{ lookup('template', 'templates/1-python36-is.yaml') }}"
#
#- name:  Python36 ImageStream
#  k8s:
#    state: "{{state}}"
#    definition: "{{ lookup('template', 'templates/2-nodejs-8-rhel7-is.yaml') }}"
#
#- name:  Postgres ImageStream
#  k8s:
#    state: "{{state}}"
#    definition: "{{ lookup('template', 'templates/4-pg-is.yaml') }}"
#
#- name:  MongoDB ImageStream
#  k8s:
#    state: "{{state}}"
#    definition: "{{ lookup('template', 'templates/5-mongo-is.yaml') }}"


# Images ImageStreams and BuildConfigs
- name:  Comments ImageStream
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/comments-is.yaml') }}"

- name:  Comment BuildConfig
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/comments-bc.yaml') }}"


- name:  Feed ImageStream
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/feed-is.yaml') }}"

- name:  Feed BuildConfig
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/feed-bc.yaml') }}"

- name:  Identity ImageStream
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/identity-is.yaml') }}"

- name: Identity BuildConfig
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/identity-bc.yaml') }}"

- name:  Identity NV ImageStream
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/identitynv-is.yaml') }}"

- name: Identity NV BuildConfig
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/identitynv-bc.yaml') }}"

- name: Likes ImageStream
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/likes-is.yaml') }}"

- name: Likes BuildConfig
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/likes-bc.yaml') }}"

- name:  Links ImageStream
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/links-is.yaml') }}"

- name:  Linke BuildConfig
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/links-bc.yaml') }}"

- name: Receiver ImageStream
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/receiver-is.yaml') }}"

- name:  Receiver BuildConfig
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/receiver-bc.yaml') }}"

- name: UI ImageStream
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/ui-is.yaml') }}"

- name:  UI BuildConfig
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/ui-bc.yaml') }}"

- name: NVUI ImageStream
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/nvui-is.yaml') }}"

- name:  NVUI BuildConfig
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/nvui-bc.yaml') }}"

- name:  Build all services
  shell: |
    oc start-build comments
    oc start-build feed
    oc start-build identity
    oc start-build likes
    oc start-build links
    oc start-build receiver
    oc start-build ui
    oc start-build ui-new-version
    oc start-build identity-new-version
  when: state  == 'present'

- name:  Delete all services
  shell: |
    oc delete build --all
  when: state  == 'absent'
