apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: "{{app_name}}"
  namespace: istio-system
spec:
  host: "feed.{{namespace}}.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: "{{feed_mtls_mode}}"
    outlierDetection:
      consecutiveErrors: 2
      interval: 40s
      baseEjectionTime: 3m
      maxEjectionPercent: 100
  subsets:
  - name: v1
    labels:
      version: v1
