apiVersion: v1
kind: DeploymentConfig
metadata:
  name: ui-new-version
  namespace: "{{namespace}}"
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: ui
        version: v2
    spec:
      containers:
      - name: ui
        image: " "
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
  triggers:
    - type: "ConfigChange"
    - type: "ImageChange"
      imageChangeParams:
        automatic: true
        containerNames:
          - "mongo-comments"
        from:
          kind: "ImageStreamTag"
          name: "ui-new-version:0.1"