apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: ui
  namespace: "{{namespace}}"
spec:
  host: ui
  subsets:
  - name: v1
    labels:
      version: v1
    trafficPolicy:
      tls:
        mode: "{{nvui_mtls_mode}}"
      loadBalancer:
        consistentHash:
          httpHeaderName: X-APP-TEST
  - name: v2
    labels:
      version: v2
    trafficPolicy:
      tls:
        mode: "{{nvui_mtls_mode}}"
      loadBalancer:
        consistentHash:
          httpHeaderName: X-APP-TEST
