apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ui
  namespace: "{{namespace}}"
spec:
  hosts:
    - frontend.nemo
    - ui
  gateways:
  - nemo-gateway
  http:
  - route:
    - destination:
        host: ui
        subset: v1
      weight: 50
    - destination:
        host: ui
        subset: v2
      weight: 50
