apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: identity
  namespace: "{{namespace}}"
spec:
  host: identity.nemo.svc.cluster.local
  trafficPolicy:
    tls:
      mode: "{{mtls_mode}}"
  subsets:
  - name: v1
    labels:
      version: v1
