apiVersion: v1
kind: ImageStream
metadata:
    name: identity
    namespace: "{{namespace}}"
spec:
    tags:
    - from:
          kind: DockerImage
          name: "docker-registry.default.svc:5000/{{namespace}}/identity"
      name: latest
      importPolicy:
          scheduled: true
