apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: pg
  namespace: "{{namespace}}"
spec:
  host: pg
  trafficPolicy:
    tls:
      mode: "{{mtls_mode}}"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: pg
  namespace: "{{namespace}}"
spec:
  hosts:
    - pg
  tcp:
  - match:
    - port: 5432
    route:
    - destination:
        host: pg
        port:
          number: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: pg
  namespace: "{{namespace}}"
spec:
  selector:
    app: pg
  ports:
  - name: pg
    port: 5432
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: pg
  namespace: "{{namespace}}"
  labels:
    app: pg
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: pg
    spec:
      containers:
      - name: pg
        image: " "
        env:
        - name: POSTGRESQL_ADMIN_PASSWORD
          value: "12345"
        ports:
        - containerPort: 5432
  triggers:
    - type: "ConfigChange"
    - type: "ImageChange"
      imageChangeParams:
        automatic: true
        containerNames:
          - "pg"
        from:
          kind: "ImageStreamTag"
          name: "postgresql:10"
          namespace: "openshift"

