- name: Build {{app_name}} Service
  block:
    - name: Create IS for {{app_name}} service
      k8s:
        state: "{{state}}"
        definition: "{{ lookup('template', 'templates/is.yaml') }}"
    - name:  Create build config for comment service
      k8s:
        state: "{{state}}"
        definition: "{{ lookup('template', 'templates/bc.yaml') }}"
    - name:  Build comment service
      shell: |
        oc start-build {{app_name}}
      when: state == "present"
  when:
  - prereq|bool == True

- name: Deploy Comments Service
  block:
    # App objects
    - name:  Receiver Deployment
      k8s:
        state: "{{state}}"
        definition: "{{ lookup('template', 'templates/dep.yaml') }}"

    # Istio objects
    - name:  Receiver DestinationRule
      k8s:
        state: "{{state}}"
        definition: "{{ lookup('template', 'templates/drule.yaml') }}"

    - name:  Receiver VirtualService
      k8s:
        state: "{{state}}"
        definition: "{{ lookup('template', 'templates/vs.yaml') }}"

    - name: Receiver DestinationRule for Istio NS
      k8s:
        state: "{{state}}"
        definition: "{{ lookup('template', 'templates/drule-for-istio-ns.yaml') }}"

    - name: Receiver Policy
      k8s:
        state: "{{state}}"
        definition: "{{ lookup('template', 'templates/policy.yaml') }}"

  when: prereq|bool == False




