# App objects
- name:  Receiver Deployment
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/dep.yaml') }}"

# Istio objects
- name:  Receiver DestinationRule
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/drule.yaml') }}"

- name:  Receiver VirtualService
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/vs.yaml') }}"

- name: Receiver DestinationRule for Istio NS
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/drule-for-istio-ns.yaml') }}"

- name: Receiver Policy
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/policy.yaml') }}"
