- name:  Receiver ImageStream
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/receiver-is.yaml') }}"

- name:  Identity BuildConfig
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/receiver-bc.yaml') }}"

- name: Fetch build build state
  k8s_facts:
    kind: BuildConfig
    api_version: build.openshift.io/v1
    namespace: "{{namespace}}"
    name: "{{receiver_bc_name}}"
  register: build_config

- name: Build Receiver docker image if it's a fresh setup
  shell: "oc start-build {{receiver_bc_name}} -n {{namespace}}"
  when:
    - build_config.resources | length > 0
    - build_config.resources[0].status.lastVersion | int == 0

# App objects
- name:  Receiver Deployment
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/dep.yaml') }}"

# Istio objects
- name:  Receiver DestinationRule
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/drule.yaml') }}"

- name:  Receiver VirtualService
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/vs.yaml') }}"
