apiVersion: v1
kind: DeploymentConfig
metadata:
  name: feed
  namespace: "{{namespace}}"
  labels:
    app: feed
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: feed
        version: v1
    spec:
      serviceAccountName: feed-sa
      containers:
      - name: feed
        image: " "
        imagePullPolicy: Always
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: "JAVA_APP_JAR"
          value: "feed-0.7-fat.jar"
        ports:
        - containerPort: 8080
  triggers:
    - type: "ConfigChange"
    - type: "ImageChange"
      imageChangeParams:
        automatic: true
        containerNames:
          - "feed"
        from:
          kind: "ImageStreamTag"
          name: "feed:0.1"
