apiVersion: apps/v1
kind: Deployment
metadata:
  name: receiver
  namespace: "{{namespace}}"
  labels:
    app: receiver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: receiver
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: receiver
        version: v1
    spec:
      serviceAccountName: receiver-sa
      containers:
      - name: receiver
        image: "docker-registry.default.svc:5000/{{namespace}}/receiver:0.1"
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        ports:
        - containerPort: 8080
