apiVersion: v1
kind: DeploymentConfig
metadata:
  name: receiver
  namespace: "{{namespace}}"
  labels:
    app: receiver
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: receiver
        version: v1
    spec:
      serviceAccountName: receiver-sa
      containers:
      - name: receiver
        image: " "
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        ports:
        - containerPort: 8080
  triggers:
    - type: "ConfigChange"
    - type: "ImageChange"
      imageChangeParams:
        automatic: true
        containerNames:
          - "comments"
        from:
          kind: "ImageStreamTag"
          name: "receiver:0.1"
