apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: feed-viewer-deleter
  namespace: "{{namespace}}"
spec:
  rules:
  - services: ["links.{{namespace}}.svc.cluster.local"]
    methods: ["GET","DELETE"]
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: receiver-writer
  namespace: "{{namespace}}"
spec:
  rules:
  - services: ["links.{{namespace}}.svc.cluster.local"]
    methods: ["GET","POST"]
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: bind-feed-viewer
  namespace: "{{namespace}}"
spec:
  subjects:
  - user: "cluster.local/ns/{{namespace}}/sa/feed-sa"
  roleRef:
    kind: ServiceRole
    name: "feed-viewer-deleter"
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: bind-receiver-writer
  namespace: "{{namespace}}"
spec:
  subjects:
  - user: "cluster.local/ns/{{namespace}}/sa/receiver-sa"
  roleRef:
    kind: ServiceRole
    name: "receiver-writer"
