apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: ui
  namespace: "{{namespace}}"
spec:
  host: ui
  trafficPolicy:
    tls:
      mode: "{{ui_mtls_mode}}"
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
