apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ui
  namespace: "{{namespace}}"
spec:
  hosts:
  - frontend.nemo
  - ui
  gateways:
  - nemo-gateway
  http:
  - match:
    - headers:
        X-APP-TEST:
          exact: test
    route:
    - destination:
        host: ui
        subset: v2
  - route:
    - destination:
        host: ui
        subset: v1
      weight: 100
