kind: Service
apiVersion: v1
metadata:
  name: likes
  namespace: "{{namespace}}"
  lables:
    app: likes
spec:
  selector:
    app: likes
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: likes
  namespace: "{{namespace}}"
  labels:
    app: likes
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: likes
        version: v1
    spec:
      containers:
      - name: likes
        image: " "
        env:
        - name: PROFILE
          value: PROD
        ports:
        - containerPort: 8080
  triggers:
    - type: "ConfigChange"
    - type: "ImageChange"
      imageChangeParams:
        automatic: true
        containerNames:
          - "likes"
        from:
          kind: "ImageStreamTag"
          name: "likes:0.1"
