apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: mongo-likes
  namespace: "{{namespace}}"
spec:
  host: mongo-likes
  trafficPolicy:
    tls:
      mode: "{{mtls_mode}}"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mongo-likes
  namespace: "{{namespace}}"
spec:
  hosts:
    - mongo-likes
  tcp:
  - match:
    - port: 27017
    route:
    - destination:
        host: mongo-likes
        port:
          number: 27017
---
kind: Service
apiVersion: v1
metadata:
  name: mongo-likes
  namespace: "{{namespace}}"
spec:
  selector:
    app: mongo-likes
  ports:
  - name: mongo
    port: 27017
---
kind: DeploymentConfig
apiVersion: "v1"
metadata:
  name: "mongo-likes"
  namespace: "{{namespace}}"
  labels:
    app: "mongo-likes"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "mongo-likes"
    spec:
      containers:
      - name: "mongo-likes"
        image: " "
        env:
        - name: MONGODB_ADMIN_PASSWORD
          value: "12345"
        ports:
        - containerPort: 27017
  triggers:
    - type: "ConfigChange"
    - type: "ImageChange"
      imageChangeParams:
        automatic: true
        containerNames:
          - "mongo-likes"
        from:
          kind: "ImageStreamTag"
          name: "{{mongodb_is}}"
          namespace: "openshift"
