apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: identity
  namespace: istio-system
spec:
  host: "identity.{{namespace}}.svc.cluster.local"
  subsets:
  - name: v1
    labels:
      version: v1
    trafficPolicy:
      tls:
        mode: "{{identity_mtls_mode}}"
      loadBalancer:
        consistentHash:
          httpHeaderName: x-app-test
          # useSourceIp: true
