kind: Service
apiVersion: v1
metadata:
  name: comments
  namespace: "{{namespace}}"
  lables:
    app: comments
spec:
  selector:
    app: comments
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: comments
  namespace: "{{namespace}}"
  labels:
    app: comments
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: comments
        version: v1
    spec:
      containers:
      - name: comments
        image: " "
        env:
        - name: MONGO_HOST
          value: mongo-comments
        ports:
        - containerPort: 8080
  triggers:
    - type: "ConfigChange"
    - type: "ImageChange"
      imageChangeParams:
        automatic: true
        containerNames:
          - "comments"
        from:
          kind: "ImageStreamTag"
          name: "comments:0.1"
