
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: comments
  namespace: "{{namespace}}"
spec:
  hosts:
    - comments
  http:
  - route:
    - destination:
        host: comments.nemo.svc.cluster.local
        subset: v1
