apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: likes
  namespace: "{{namespace}}"
spec:
  hosts:
    - likes
  http:
  - fault:
      delay:
        fixedDelay: 10s
        percent: 100
    match:
    - headers:
        X-APP-TEST:
          exact: test
    route:
    - destination:
        host: likes
        subset: v1
  - route:
    - destination:
        host: likes
        subset: v1
