- name: Build {{app_name}} Service
  block:
  - name: Create IS for {{app_name}} service
    k8s:
      state: "{{state}}"
      definition: "{{ lookup('template', 'templates/is.yaml') }}"
  - name:  Create build config for comment service
    k8s:
      state: "{{state}}"
      definition: "{{ lookup('template', 'templates/bc.yaml') }}"
  - name:  Build comment service
    shell: |
      oc start-build {{app_name}}
    when: state == "present"
  when:
  - prereq|bool == True

- name: Deploy Comments Service
  block:
  - name:  MongoDB instace
    k8s:
      state: "{{state}}"
      definition: "{{ lookup('template', 'templates/mongo-dep.yaml') }}"
  - name:  Comments Deployment
    k8s:
      state: "{{state}}"
      definition: "{{ lookup('template', 'templates/dep.yaml') }}"
  - name:  Comments DestinationRule
    k8s:
      state: "{{state}}"
      definition: "{{ lookup('template', 'templates/drule.yaml') }}"
  - name:  Comments VirtualService
    k8s:
      state: "{{state}}"
      definition: "{{ lookup('template', 'templates/vs.yaml') }}"
  when: prereq|bool == False
