kind: Service
apiVersion: v1
metadata:
  name: links
  namespace: "{{namespace}}"
  lables:
    app: links
spec:
  selector:
    app: links
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
kind: DeploymentConfig
apiVersion: "v1"
metadata:
  name: "{{app_name}}"
  namespace: "{{namespace}}"
  labels:
    app: "{{app_name}}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{app_name}}"
    spec:
      containers:
      - name: "{{app_name}}"
        image: " "
        env:
        - name: PROFILE
          value: PROD
        ports:
        - containerPort: 8080
  triggers:
    - type: "ConfigChange"
    - type: "ImageChange"
      imageChangeParams:
        automatic: true
        containerNames:
          - "{{app_name}}"
        from:
          kind: "ImageStreamTag"
          name: "{{app_istag}}"
