kind: Service
apiVersion: v1
metadata:
  name: links
  namespace: "{{namespace}}"
  lables:
    app: links
spec:
  selector:
    app: links
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: links
  namespace: "{{namespace}}"
  labels:
    app: links
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: links
        version: v1
    spec:
      containers:
      - name: links
        image: " "
        imagePullPolicy: Always
        env:
        - name: PROFILE
          value: PROD
        ports:
        - containerPort: 8080
  triggers:
    - type: "ConfigChange"
    - type: "ImageChange"
      imageChangeParams:
        automatic: true
        containerNames:
          - "links"
        from:
          kind: "ImageStreamTag"
          name: "links:0.1"
