
kind: Service
apiVersion: v1
metadata:
  name: feed-debug
  namespace: "{{namespace}}"
  lables:
    app: feed-debug
spec:
  selector:
    debug: feed-debug
  ports:
  - name: xdebug
    port: 5005
---
kind: DeploymentConfig
apiVersion: "v1"
metadata:
  name: feed-debug
  namespace: "{{namespace}}"
  labels:
    app: "{{app_name}}"
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: "{{app_name}}"
        version: v1d
        debug: feed-debug
    spec:
      containers:
      - name: "{{app_name}}"
        image: " "
        command: ["/bin/bash","-c", "java -Xdebug -Xrunjdwp:transport=dt_socket,server=y,address=5005,suspend=y -jar /deployments/feed-0.7-fat.jar"]
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: "JAVA_APP_JAR"
          value: "feed-0.7-fat.jar"
        ports:
        - containerPort: 8080
        - containerPort: 5005
  triggers:
    - type: "ConfigChange"
    - type: "ImageChange"
      imageChangeParams:
        automatic: true
        containerNames:
          - "{{app_name}}"
        from:
          kind: "ImageStreamTag"
          name: "{{app_istag}}"
