- name:  Feed ImageStream
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/feed-is.yaml') }}"

- name:  Feed BuildConfig
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/feed-bc.yaml') }}"

- name: Fetch build config state
  k8s_facts:
    kind: BuildConfig
    api_version: build.openshift.io/v1
    namespace: "{{namespace}}"
    name: "{{feed_bc_name}}"
  register: build_config

- name: Build Feed docker image if it's a fresh setup
  shell: "oc start-build {{ui_bc_name}} -n {{namespace}}"
  when:
    - build_config.resources | length > 0
    - build_config.resources[0].status.lastVersion | int == 0

# App objects
- name:  Feed Deployment
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/dep.yaml') }}"

# Istio objects
- name:  Feed DestinationRule
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/drule.yaml') }}"

- name:  Feed VirtualService
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/vs.yaml') }}"
