# App objects
- name:  Feed Deployment
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/dep.yaml') }}"

# Istio objects
- name:  Feed DestinationRule
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/drule.yaml') }}"

- name:  Feed VirtualService
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/vs.yaml') }}"

- name:  Feed DestinationRule for Istio NS
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/drule-for-istio-ns.yaml') }}"

- name:  Feed Policy
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/policy.yaml') }}"
